### PR TITLE
Add support for pf2e

### PR DESCRIPTION
**Pull request by xdy**
As pf2e has the same pc actor type as dnd5e, I just changed the condition.

### CODE REVIEW

**Comment by jagoe** [comment]
Great! Thanks for your contribution 👍

**Comment by jagoe** [comment]
@xdy The actions don't seem to run. Can you try pushing an empty commit (`git commit -m 'Rebuild' --allow-empty`)? Just want to check if it's a fluke or if I need to change something in my workflow.

**Comment by xdy** [comment]
Sure. But I think you'll need to change the first couple lines of your workflow to:
```
name: Module CI/CD

on:
  pull_request:
  push:
  workflow_dispatch:
```
and change this:
```
 release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
```
to something like:
```
 release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main') && github.repository == 'jagoe/fvtt-module-focus-sheet'
```

The above is obviously untested, but you can compare with what I do here: https://github.com/xdy/xdy-pf2e-workbench/blob/main/.github/workflows/test-release.yml

**Comment by jagoe** [comment]
`github.repository == 'jagoe/fvtt-module-focus-sheet'` seems a bit inelegant to me, but I see what you mean 😄 I also like the automated module release to Foundry and will definitely rip that off as well, haha.

Sadly, the `build` and `test` jobs don't seem to run for PRs (probably permission issues?), but I'll make sure your change gets merged before researching a solution.

**Comment by jagoe** [comment]
I noticed one thing: Could you adjust the readme to include pf2e as a supported system? Once that's done, I'll merge your PR.

**Comment by xdy** [comment]
> `github.repository == 'jagoe/fvtt-module-focus-sheet'` seems a bit inelegant to me, but I see what you mean 😄 I also like the automated module release to Foundry and will definitely rip that off as well, haha.
> 
> Sadly, the `build` and `test` jobs don't seem to run for PRs (probably permission issues?), but I'll make sure your change gets merged before researching a solution.

Yeah. I just couldn't think of a better way to avoid starting releases for forks all the time. :)

**Review by jagoe — CHANGES_REQUESTED** [review]

**Review by jagoe — APPROVED** [review]

**Pull request merged**
